#!/bin/bash

echo "=================================="
echo "Google Sign-In Android Fix Script"
echo "=================================="
echo ""

# Get SHA-1 fingerprint
echo "📍 Step 1: Getting your SHA-1 fingerprint..."
echo ""
SHA1=$(keytool -list -v -alias androiddebugkey -keystore ~/.android/debug.keystore -storepass android 2>/dev/null | grep "SHA1:" | cut -d' ' -f3)
SHA256=$(keytool -list -v -alias androiddebugkey -keystore ~/.android/debug.keystore -storepass android 2>/dev/null | grep "SHA256:" | cut -d' ' -f3)

echo "✅ Your Debug SHA-1:"
echo "   $SHA1"
echo ""
echo "✅ Your Debug SHA-256:"
echo "   $SHA256"
echo ""

# Instructions
echo "=================================="
echo "🔧 FOLLOW THESE STEPS:"
echo "=================================="
echo ""
echo "1️⃣  GO TO FIREBASE CONSOLE"
echo "   → https://console.firebase.google.com/"
echo ""
echo "2️⃣  SELECT PROJECT: chalmumbai"
echo ""
echo "3️⃣  CLICK GEAR ICON ⚙️  → Project Settings"
echo ""
echo "4️⃣  SCROLL DOWN TO 'Your apps' SECTION"
echo ""
echo "5️⃣  FIND YOUR ANDROID APP: com.kaam25.kaam25"
echo ""
echo "6️⃣  CLICK 'Add fingerprint' BUTTON"
echo ""
echo "7️⃣  PASTE THIS SHA-1:"
echo "   $SHA1"
echo ""
echo "8️⃣  CLICK 'Save'"
echo ""
echo "9️⃣  (OPTIONAL) ADD SHA-256 AS WELL:"
echo "   $SHA256"
echo ""
echo "🔟  DOWNLOAD NEW google-services.json"
echo "   → Click on your Android app"
echo "   → Click 'google-services.json'"
echo "   → Replace file at: android/app/google-services.json"
echo ""
echo "=================================="
echo "AFTER ADDING SHA-1, RUN:"
echo "=================================="
echo "cd '$(pwd)'"
echo "flutter clean"
echo "flutter pub get"
echo "flutter run -d emulator-5554"
echo ""
echo "=================================="
echo "✅ VERIFICATION:"
echo "=================================="
echo "After running, try Google Sign-In and check logs for:"
echo "  🔐 Attempting Google sign-in..."
echo "  ✅ Google sign-in successful"
echo ""
echo "If you see error code 7 or 10, SHA-1 needs to be added!"
echo "=================================="
