// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'FirebaseOptions have not been configured for web - add web support if needed.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'FirebaseOptions have not been configured for Windows - add desktop support if needed.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'FirebaseOptions have not been configured for Linux - add desktop support if needed.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG17qWvlsswS40mqtAKm5ghXRwfwUXpI0',
    appId: '1:388870218082:android:b0f8f0f7bd904109db4c3b',
    messagingSenderId: '388870218082',
    projectId: 'chalmumbai',
    storageBucket: 'chalmumbai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiAXd95-NFXpWothq8zLglK69l1lzQW_o',
    appId: '1:388870218082:ios:16bbb8e17a94c2dadb4c3b',
    messagingSenderId: '388870218082',
    projectId: 'chalmumbai',
    storageBucket: 'chalmumbai.firebasestorage.app',
    iosClientId:
        '388870218082-ute4pugo7ebkt81b0q6fmmhjikdgksu6.apps.googleusercontent.com',
    iosBundleId: 'com.kaam25.kaam25',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiAXd95-NFXpWothq8zLglK69l1lzQW_o',
    appId: '1:388870218082:ios:16bbb8e17a94c2dadb4c3b',
    messagingSenderId: '388870218082',
    projectId: 'chalmumbai',
    storageBucket: 'chalmumbai.firebasestorage.app',
    iosClientId:
        '388870218082-ute4pugo7ebkt81b0q6fmmhjikdgksu6.apps.googleusercontent.com',
    iosBundleId: 'com.kaam25.kaam25',
  );
}
